[theme]
primaryColor = "#4CAF50"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#262626"
textColor = "#FFFFFF"


[theme]
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#000000"
